/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CandidateCreateNestedManyWithoutJobProfilesInput } from "./CandidateCreateNestedManyWithoutJobProfilesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CompanyCreateNestedManyWithoutJobProfilesInput } from "./CompanyCreateNestedManyWithoutJobProfilesInput";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { ComparisonCreateNestedManyWithoutJobProfilesInput } from "./ComparisonCreateNestedManyWithoutJobProfilesInput";

@InputType()
class JobProfileCreateInput {
  @ApiProperty({
    required: false,
    type: () => CandidateCreateNestedManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => CandidateCreateNestedManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => CandidateCreateNestedManyWithoutJobProfilesInput, {
    nullable: true,
  })
  candidates?: CandidateCreateNestedManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: () => CompanyCreateNestedManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => CompanyCreateNestedManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => CompanyCreateNestedManyWithoutJobProfilesInput, {
    nullable: true,
  })
  companies?: CompanyCreateNestedManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ComparisonCreateNestedManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => ComparisonCreateNestedManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => ComparisonCreateNestedManyWithoutJobProfilesInput, {
    nullable: true,
  })
  comparisons?: ComparisonCreateNestedManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requirements?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { JobProfileCreateInput as JobProfileCreateInput };
