/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CandidateUpdateManyWithoutJobProfilesInput } from "./CandidateUpdateManyWithoutJobProfilesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CompanyUpdateManyWithoutJobProfilesInput } from "./CompanyUpdateManyWithoutJobProfilesInput";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { ComparisonUpdateManyWithoutJobProfilesInput } from "./ComparisonUpdateManyWithoutJobProfilesInput";

@InputType()
class JobProfileUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CandidateUpdateManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => CandidateUpdateManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => CandidateUpdateManyWithoutJobProfilesInput, {
    nullable: true,
  })
  candidates?: CandidateUpdateManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: () => CompanyUpdateManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => CompanyUpdateManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => CompanyUpdateManyWithoutJobProfilesInput, {
    nullable: true,
  })
  companies?: CompanyUpdateManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ComparisonUpdateManyWithoutJobProfilesInput,
  })
  @ValidateNested()
  @Type(() => ComparisonUpdateManyWithoutJobProfilesInput)
  @IsOptional()
  @Field(() => ComparisonUpdateManyWithoutJobProfilesInput, {
    nullable: true,
  })
  comparisons?: ComparisonUpdateManyWithoutJobProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requirements?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { JobProfileUpdateInput as JobProfileUpdateInput };
